### ISSUE TITLE
Feature: Enemy States

### ISSUE THREAD

**Issue by WestonVincze** [WestonVincze/Dwarf-Forges#3]
## Description
We need to define the possible states for the dwarves and have the ability to change into another state on a trigger. 

Dwarf States:
- moving (this could be broken down into multiple movement patterns)
- pulling forge
- dead
- (???)

State transitions will likely only occur on specific triggers (spawned in, killed, close to forge, etc) so we probably do not need any sort of brain.

## A/C
- Dwarves have multiple states and can switch between them

**Comment by Eluem** [comment]
I didn't implement a "Dead" state as of yet... It didn't seem necessary since they just instantly die.. but now that I'm thinking about it, I should probably just add a timer to the destroy call and put them in a "dead" state that will last until they are deleted.

**Comment by Eluem** [comment]
I implemented a proper "Dead" state in the brain as well as some logic that gets registered to be triggered on the death event for things like disabling the rope and launching the dwarf in a random direction (just for testing for now).
